# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Minh Luu
name: Minh Luu (Nguyen Hoang)
position: AI Resident
email: hoangminh291101@gmail.com
description: >-
  I am a researcher in 3D computer vision, generative models, and computer graphics. I am currently a AI Resident at [VinAI](https://www.vinai.io/).

  I received my Bachelor of Computer Science from the [Ho Chi Minh University of Technology](https://hcmut.edu.vn/) in 2023.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minhluu2911.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: minhluu291101
github_username: Minhluu2911
google_scholar: Q7C_mlIAAAAJ
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
