# Site configuration for Jekyll personal website
# https://jekyllrb.com/docs/configuration/

# Site metadata
title: Minh Luu
name: Minh Luu (Nguyen Hoang)
position: Master Student @ University of Illinois at Urbana-Champaign (UIUC)
email: hoangminh291101@gmail.com

# Description for meta tags and social sharing
description: >-
  I am a researcher in 3D computer vision, generative models, and computer graphics. 
  I am currently an AI Resident at [VinAI](https://www.vinai.io/).
  
  I received my Bachelor of Computer Science from the 
  [Ho Chi Minh University of Technology](https://hcmut.edu.vn/) in 2023.

# Site URLs and paths
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minhluu2911.com" # the base hostname & protocol for your site

# Social media usernames (without @ or URLs)
twitter_username: minhluu291101
github_username: Minhluu2911
google_scholar: Q7C_mlIAAAAJ

# Analytics (uncomment to enable)
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SASS configuration for optimized CSS
sass:
  style: compressed # Compress CSS for production
  quiet_deps: true

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Performance optimizations
include:
  - _redirects

# Exclude development and build files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .git/

# Collections and defaults (for future extensibility)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Minh Luu"

# SEO and performance settings
timezone: Asia/Ho_Chi_Minh
lang: en-US

# Site features
future: false
unpublished: false
safe: true
