# Site configuration for Jekyll personal website
# https://jekyllrb.com/docs/configuration/

# Site metadata
title: Minh Luu
name: Minh Luu (Nguyen Hoang)
position: MS CS @ University of Illinois at Urbana-Champaign (UIUC)
email: hoangminh291101@gmail.com

# Description for meta tags and social sharing
description: >-
  <p>Hi, I'm currently a Master student in Computer Science (MS CS) at <a href="https://siebelschool.illinois.edu/admissions/graduate">University of Illinois at Urbana-Champaign (UIUC)</a> in Fall 2025. 
  Previously, I was an AI Research Resident at <a href="https://www.vinai.io/">VinAI Research (acquired by Qualcomm)</a>, working on 3D generative models and 3D scene understanding mentored by <a href="https://www.khoinguyen.org/">Dr. Khoi Nguyen</a> and <a href="https://sonhua.github.io/">Prof. Binh-Son Hua</a>. I earned my B.S. in Computer Science from <a href="https://hcmut.edu.vn/">Ho Chi Minh University of Technology</a> in 2023.
  <br>
  <br>
  I'm interested in 3D vision, generative models, and computer graphics.

# Site URLs and paths
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minhluu2911.com" # the base hostname & protocol for your site

# Social media usernames (without @ or URLs)
twitter_username: minhluu291101
github_username: Minhluu2911
google_scholar: Q7C_mlIAAAAJ

# Analytics (uncomment to enable)
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SASS configuration for optimized CSS
sass:
  style: compressed # Compress CSS for production
  quiet_deps: true

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Performance optimizations
include:
  - _redirects

# Exclude development and build files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .git/

# Collections and defaults (for future extensibility)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Minh Luu"

# SEO and performance settings
timezone: Asia/Ho_Chi_Minh
lang: en-US

# Site features
future: false
unpublished: false
safe: true
